name: Apptainer Build and Publish

on:
  push:
    branches:
      - apptainer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0

    - name: Build SIF image
      run: |
        apptainer build voluseg_latest.sif docker://ghcr.io/mikarubi/voluseg/voluseg:latest

    - name: Login and Deploy Container
      run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
