name: Tests

on:
  push:
    branches:
      - master
      - testing
  pull_request:
    branches:
      - master
      - testing

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          # - windows-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'

    name: ${{ matrix.os }} Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      # Download and install ANTs
      - name: Install ANTs
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          wget https://github.com/ANTsX/ANTs/releases/download/v2.5.3/ants-2.5.3-ubuntu-20.04-X64-gcc.zip
          unzip ants-2.5.3-ubuntu-20.04-X64-gcc.zip -d $HOME/
          rm ants-2.5.3-ubuntu-20.04-X64-gcc.zip
          echo "ANTs installed successfully"

      - name: Install ANTs on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          curl -L -o $HOME/ants-2.5.3-macos-14-ARM64-clang.zip https://github.com/ANTsX/ANTs/releases/download/v2.5.3/ants-2.5.3-macos-14-ARM64-clang.zip
          unzip $HOME/ants-2.5.3-macos-14-ARM64-clang.zip -d $HOME/
          rm $HOME/ants-2.5.3-macos-14-ARM64-clang.zip
          echo "ANTs installed successfully on macOS"

      # - name: Install ANTs on Windows
      #   if: startsWith(matrix.os, 'windows')
      #   run: |
      #     Invoke-WebRequest -Uri https://github.com/ANTsX/ANTs/releases/download/v2.5.3/ants-2.5.3-windows-2022-X64-VS2019.zip -OutFile $env:USERPROFILE\\ants-2.5.3-windows-2022-X64-VS2019.zip
      #     Expand-Archive -Path $env:USERPROFILE\\ants-2.5.3-windows-2022-X64-VS2019.zip -DestinationPath $env:USERPROFILE\\ants-2.5.3
      #     Remove-Item $env:USERPROFILE\\ants-2.5.3-windows-2022-X64-VS2019.zip
      #     echo "ANTs installed successfully on Windows"

      # Install voluseg and dependencies
      - name: Install voluseg
        run: |
          python -m pip install --upgrade pip
          pip install -e .   
          pip install -r requirements.txt -r tests/requirements.txt --no-cache-dir

      # Tests and coverage
      - name: Clear previous coverage data
        run: coverage erase

      # Run .h5 tests
      - name: Run .h5 tests
        run: |
          export PATH="$HOME/ants-2.5.3/bin:$PATH"
          coverage run --source=voluseg -m pytest -m h5 -s -v --tb=short


      # Archive only block00000.hdf5 for NWB comparison
      - name: Archive minimal .h5 output for comparison
        run: |
         TMPDIR=$(find /tmp -maxdepth 1 -type d -name 'pytest-of-*' | head -n 1)
          if [ -z "$TMPDIR" ]; then
            echo "No pytest tmpdir found"; exit 1
          fi
          mkdir -p h5_minimal
          find "$TMPDIR" -path "*/cells/0/block00000.hdf5" -exec cp --parents {} h5_minimal \;
          tar -czf output_h5_min.tar.gz -C h5_minimal .
          rm -rf h5_minimal

      # Restore minimal .h5 output before running .nwb tests
      - name: Restore .h5 output for .nwb comparison
        run: |
          TMPDIR=$(find /tmp -maxdepth 1 -type d -name 'pytest-of-*' | head -n 1)
          if [ -z "$TMPDIR" ]; then
            echo "No pytest tmpdir found"; exit 1
          fi
          tar -xzf output_h5_min.tar.gz -C "$TMPDIR"


      # Run .nwb tests
      - name: Run .nwb tests
        run: |
          export PATH="$HOME/ants-2.5.3/bin:$PATH"
          coverage run --append -m pytest -m nwb -s -v --tb=short

      # Final cleanup
      - name: Final cleanup
        if: always()
        run: |
          rm -f output_h5_min.tar.gz
          rm -rf .pytest_cache

      # - name: Run tests with pytest on Windows
      #   if: startsWith(matrix.os, 'windows')
      #   env:
      #     ANTS_PATH: "%USERPROFILE%/ants-2.5.3/bin"
      #   run: |
      #     pytest --cov=voluseg --cov-report=term-missing --cov-report=html --cov-report=xml -s -v --tb=short

      - name: Generate coverage report
        run: coverage report -m

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

