name: Tests with Spark

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'
        spark:
          - 3.4.0
          - 3.5.2

    name: ${{ matrix.os }} Python ${{ matrix.python }} Spark ${{ matrix.spark }}
    runs-on: ${{ matrix.os }}

    env:
      ANTS_PATH: $HOME/ants-2.5.3/bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      # Download and install ANTs
      - name: Install ANTs
        run: |
          wget https://github.com/ANTsX/ANTs/releases/download/v2.5.3/ants-2.5.3-ubuntu-20.04-X64-gcc.zip
          unzip ants-2.5.3-ubuntu-20.04-X64-gcc.zip -d $HOME/
          rm ants-2.5.3-ubuntu-20.04-X64-gcc.zip
          echo "ANTs installed successfully"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt --no-cache-dir

      - name: Install voluseg
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pyspark==${{ matrix.spark }} --no-cache-dir
          pip install . --no-cache-dir

      - name: Clear previous coverage data
        run: coverage erase

      - name: Run tests with pytest
        run: |
          pytest --cov=voluseg --cov-report=term-missing --cov-report=html --cov-report=xml -s -v --tb=short

      - name: Generate coverage report
        run: coverage report -m

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
